terraform {
  required_version = ">= 1.0.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }
  }
}

variable "environment" {
  default = "learning"
}

resource "local_file" "runbook" {
  filename = "${path.module}/runbook-${var.environment}.md"
  content  = "# ${var.environment} runbook\n\nGenerated by Terraform.\n"
}

output "runbook_path" {
  value = local_file.runbook.filename
}
